# Generated by Django 5.1.7 on 2025-03-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capa', models.ImageField(blank=True, null=True, upload_to='capas/', verbose_name='Capa')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtítulo')),
                ('projeto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Projeto')),
                ('organizadores', models.CharField(blank=True, max_length=255, null=True, verbose_name='Organizadores')),
                ('autores', models.TextField(blank=True, null=True, verbose_name='Autores')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo')),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, verbose_name='ISBN')),
                ('ano_publicacao', models.IntegerField(verbose_name='Ano de Publicação')),
                ('numero_paginas', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Páginas')),
                ('idioma', models.CharField(blank=True, max_length=50, null=True, verbose_name='Idioma')),
                ('formato', models.CharField(blank=True, max_length=100, null=True, verbose_name='Formato')),
                ('disponibilidade', models.CharField(blank=True, max_length=255, null=True, verbose_name='Disponibilidade')),
                ('dimensoes', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dimensões (cm)')),
                ('classificacao_tema', models.CharField(blank=True, max_length=255, null=True, verbose_name='Classificação/Tema')),
                ('cdu_thema', models.CharField(blank=True, max_length=255, null=True, verbose_name='CDU / Thema')),
                ('palavras_chave', models.TextField(blank=True, null=True, verbose_name='Palavras-chave')),
                ('resumo', models.TextField(blank=True, null=True, verbose_name='Resumo')),
                ('link_pdf', models.URLField(blank=True, null=True, verbose_name='Link PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
