# Generated by Django 5.1.7 on 2025-03-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=models.CharField(max_length=20, null=True, verbose_name='ISBN'),
        ),
    ]
