# Generated by Django 5.1.7 on 2025-03-31 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_alter_livro_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=models.CharField(max_length=40, verbose_name='ISBN'),
        ),
    ]
