# Generated by Django 5.1.7 on 2025-03-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_alter_livro_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='ano_publicacao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano de Publicação'),
        ),
    ]
